/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package taskquest.app

import javafx.application.Application
import javafx.stage.Stage
import taskquest.app.javafx.*

// for outlining layout borders
val debugMode = false
val cssLayout = """
            -fx-border-color: black;
            -fx-border-insets: 5;
            -fx-border-width: 1;
            -fx-border-style: dashed;
            
            """.trimIndent()

class App: Application() {
    override fun start(stage: Stage?) {
        val display = MainBoardDisplay()
        display.start_display(stage)
    }
}

fun main() {
    Application.launch(App::class.java)
}
