/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package taskquest.console

class MessageUtils {
    companion object {
        fun getMessage(): String = "Console       Demo!"
    }
}
